import { useState } from "react";
import { ChevronDown, ChevronUp, Sparkles } from "lucide-react";

interface SwapOption {
  swap: string;
  reason: string;
}

interface AIInsightsPanelProps {
  reasoning: string;
  swapOptions?: SwapOption[] | null;
}

export function AIInsightsPanel({ reasoning, swapOptions }: AIInsightsPanelProps) {
  const [open, setOpen] = useState(false);

  return (
    <section className="rounded-lg border border-pitch-400/30 bg-pitch-400/5">
      {/* Header — always visible, acts as the toggle */}
      <button
        className="flex w-full items-center justify-between gap-2 p-4 text-left"
        onClick={() => setOpen((v) => !v)}
      >
        <div className="flex items-center gap-2 min-w-0">
          <Sparkles className="shrink-0 text-pitch-400" size={16} />
          <span className="font-display text-sm font-bold text-pitch-400">AI Team Analysis</span>
        </div>
        <span className="shrink-0 text-white/55 text-xs">
          {open ? "hide" : "show"}
        </span>
      </button>

      {open && (
        <div className="border-t border-pitch-400/20 px-4 pb-4 pt-3 grid gap-4">
          {/* Reasoning */}
          <div>
            <p className="mb-1.5 text-[10px] font-bold uppercase tracking-widest text-white/55">
              Why this split?
            </p>
            <p className="text-sm leading-relaxed text-white/75">{reasoning}</p>
          </div>

          {/* Swap options */}
          {swapOptions && swapOptions.length > 0 && (
            <div>
              <p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-white/55">
                Suggested swaps
              </p>
              <div className="grid gap-2">
                {swapOptions.map((opt, i) => (
                  <div key={i} className="rounded-md border border-white/[0.06] bg-white/[0.03] p-3">
                    <p className="text-xs font-semibold text-white/85 leading-snug">{opt.swap}</p>
                    <p className="mt-1 text-xs text-white/50 leading-relaxed">{opt.reason}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <p className="text-[10px] text-white/25 italic">Generated by Claude AI · For transparency only</p>
        </div>
      )}
    </section>
  );
}
