services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  backend:
    build: ./backend
    environment:
      ENVIRONMENT: production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 3
    ports:
      - "8000:8000"

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - miniodata:/data

volumes:
  miniodata:
